{% set name = "libxkbcommon" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xkbcommon/{{ name }}/archive/xkbcommon-{{ version }}.tar.gz
  sha256: 4aa6c1cad7dce1238d6f48b6729f1998c7e3f0667a21100d5268c91a5830ad7b

build:
  number: 1
  skip: true  # [win or osx]
  missing_dso_whitelist:
    - /lib/libc.so.6
  run_exports:
    - {{ pin_subpackage('libxkbcommon') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - m4
    - bison
    - cmake
    - pkg-config
  host:
    - xorg-libxau
    - libxcb
    - xorg-xproto
    - xcb-proto
    - pthread-stubs
    - libxml2
  run:
    - xkeyboard-config

test:
  commands:
    - test -f "${PREFIX}/lib/libxkbcommon${SHLIB_EXT}"
    - xkbcli --help

about:
  home: https://github.com/xkbcommon/libxkbcommon
  license: MIT/X11 Derivative
  license_family: MIT
  license_file: LICENSE
  summary: keymap handling library for toolkits and window systems
  description: |
    libxkbcommon is a keyboard keymap compiler and support library which
    processes a reduced subset of keymaps as defined by the XKB (X Keyboard
    Extension) specification.
  doc_url: https://xkbcommon.org/
  dev_url: https://github.com/xkbcommon/libxkbcommon

extra:
  recipe-maintainers:
    - scopatz
    - hmaarrfk
